# Generated by Django 3.0.8 on 2020-10-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_steamuser_can_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='can_control',
            field=models.BooleanField(default=False, verbose_name='Can control the servers'),
        ),
    ]
