# Generated by Django 3.0.8 on 2020-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201023_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='can_accept_awp',
            field=models.BooleanField(default=False, verbose_name='Can accept awp applications'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='can_accept_retake',
            field=models.BooleanField(default=False, verbose_name='Can accept retake applications'),
        ),
    ]
