# Generated by Django 3.0.5 on 2021-03-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201122_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='loccountrycode',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
