# Generated by Django 3.0.8 on 2020-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Discord', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Experience', models.CharField(max_length=100)),
                ('Experience_more', models.TextField()),
                ('Reason', models.TextField()),
                ('SteamID', models.CharField(max_length=30)),
            ],
        ),
    ]
