# Generated by Django 3.0.8 on 2020-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0002_applicationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'verbose_name_plural': 'Moderator Applications'},
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='Name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
