# Generated by Django 3.0.8 on 2020-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0003_auto_20200910_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='Name',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
