# Generated by Django 3.0.8 on 2020-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0004_auto_20200910_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
