# Generated by Django 3.0.8 on 2020-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0006_applicationmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='Status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
