# Generated by Django 3.0.8 on 2020-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0008_auto_20201022_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='path',
        ),
        migrations.AddField(
            model_name='server',
            name='instance_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
