# Generated by Django 3.0.8 on 2020-10-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0009_auto_20201023_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostactive_retake',
            fields=[
                ('playername', models.CharField(max_length=128)),
                ('steamid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_accountuse', models.IntegerField()),
                ('timect', models.IntegerField(blank=True, db_column='timeCT', null=True)),
                ('timett', models.IntegerField(blank=True, db_column='timeTT', null=True)),
                ('timespe', models.IntegerField(blank=True, db_column='timeSPE', null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mostactive_retake',
                'managed': False,
            },
        ),
    ]
