# Generated by Django 3.0.8 on 2020-10-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0010_mostactive_retake'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mostactive_retake',
            table='mostactive',
        ),
    ]
