# Generated by Django 3.0.8 on 2020-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0011_auto_20201031_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationModel',
        ),
    ]
