# Generated by Django 3.0.5 on 2021-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0012_delete_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercount',
            name='current_map',
            field=models.CharField(default='', max_length=150),
        ),
    ]
