# Generated by Django 3.0.5 on 2021-04-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0014_playercount_isdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mostactive_awp',
        ),
        migrations.DeleteModel(
            name='Mostactive_retake',
        ),
    ]
