# Generated by Django 3.0.5 on 2021-04-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0015_auto_20210423_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerCount',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
