# Generated by Django 3.0.5 on 2021-07-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0016_auto_20210425_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donators',
        ),
    ]
