# Generated by Django 3.0.5 on 2021-07-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensor_site', '0017_delete_donators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank_awp',
        ),
        migrations.DeleteModel(
            name='Rank_retake',
        ),
    ]
