# Generated by Django 3.0.5 on 2021-03-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.CharField(max_length=50)),
                ('Comment', models.TextField()),
                ('Vote', models.BooleanField(blank=True, null=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminform.ApplicationModel')),
            ],
            options={
                'verbose_name_plural': 'Moderator Applications',
            },
        ),
    ]
