# Generated by Django 3.0.5 on 2021-07-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbadmins',
            options={'managed': False, 'verbose_name_plural': 'SB Admins'},
        ),
        migrations.AlterModelOptions(
            name='sbprotests',
            options={'managed': False, 'verbose_name_plural': 'SB Protests'},
        ),
        migrations.AlterModelOptions(
            name='sbservers',
            options={'managed': False, 'verbose_name_plural': 'SB Servers'},
        ),
    ]
