# Generated by Django 3.0.5 on 2021-07-02 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvip',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('playername', models.CharField(max_length=200)),
                ('playerid', models.CharField(max_length=20, unique=True)),
                ('enddate', models.DateTimeField()),
                ('admin_playername', models.CharField(max_length=36)),
                ('admin_playerid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tVip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SteamID', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 2, 23, 7, 48, 616662, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Donators',
            },
        ),
    ]
