version: '3.8'

services:
  django:
    build:
      context: ../
      dockerfile: deployment/containers/django/Dockerfile
    restart: always
    volumes:
      - static_volume:/home/server/tensor/staticfiles
      - media_volume:/home/server/tensor/mediafiles
    ports:
      - "8084:8000"
    environment:
      - DB_AWP_PASS
      - DB_TENSOR_PASS
      - DB_SURF_PASS
      - DB_SOURCEBANS_PASS
      - DB_RETAKES_PASS
      - EMAIL_PASS
      - STEAM_API_KEY
      - SECRET_KEY
      - DISCORD_WEBHOOK_MODERATION
      - DISCORD_WEBHOOK_SERVER_STATUS
      - DISCORD_WEBHOOK_AWP_RANK
      - DISCORD_WEBHOOK_BAN_PROTEST
      - PAYPAL_EMAIL
      - PAYPAL_TEST_EMAIL
      - PAYPAL_CLIENT_ID
      - ADMIN_EMAIL
    env_file:
      - ./.env

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external: true
    name: external