version: '3.8'

services:
  django:
    build:
      context: ../
      dockerfile: deployment/containers/django/Dockerfile
    restart: always
    volumes:
      - static_volume:/home/server/tensor/staticfiles
      - media_volume:/home/server/tensor/mediafiles
    ports:
      - "8084:8000"
    env_file:
      - ./.env

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external: true
    name: external