version: '3.8'

services:
  django:
    build:
      context: ../
      dockerfile: deployment/containers/django/Dockerfile
    command: gunicorn Tensor.wsgi:application --log-level info --log-file=- --name tensor -b 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/home/server/tensor/static
      - media_volume:/home/server/tensor/media
    ports:
      - 8000:8000
    env_file:
      - ./.env

  nginx:
    build: ./containers/nginx
    ports:
      - 1337:1337
    volumes:
      - ../server:/var/app
      - static_volume:/home/server/tensor/static/
      - media_volume:/home/server/tensor/media/
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
