# Generated by Django 3.0.5 on 2021-04-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('instance_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('player_count', models.IntegerField()),
                ('max_player', models.IntegerField()),
                ('isdown', models.BooleanField(default=False)),
                ('current_map', models.CharField(default='', max_length=150)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
    ]
