# Generated by Django 3.0.5 on 2021-04-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20210425_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercount',
            old_name='Name',
            new_name='server',
        ),
    ]
