# Generated by Django 3.0.5 on 2021-07-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20210426_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercount',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playercount', to='servers.Server'),
        ),
    ]
