# Generated by Django 3.0.5 on 2021-07-12 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20210710_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerControlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 12, 11, 26, 5, 90887, tzinfo=utc))),
                ('uuid', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('status', models.IntegerField(default=-1)),
                ('accessed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='sshport',
            field=models.IntegerField(default=12345),
        ),
    ]
