# Generated by Django 3.0.5 on 2021-07-12 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20210712_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercontrolmodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
