# Generated by Django 3.0.5 on 2021-07-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20210712_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servercontrolmodel',
            name='accessed',
        ),
    ]
