# Generated by Django 3.0.5 on 2020-08-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
